/**
 * Defines the graph editor model.
 * <p>
 * Classes are auto generated by Eclipse EMF, see <code>graph.ecore</code> and
 * <code>graph.genmodel</code>
 */
module eu.eckig.grapheditor.model
{
    requires transitive org.eclipse.emf.ecore;
    requires org.eclipse.emf.common;
    
    exports de.tesis.dynaware.grapheditor.model;
}